sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /pr2/passthrough/points #replace with /pr2/3d_map/points when running your own code
    max_range: 2.5
    frame_subsample: 1
    point_subsample: 1
    padding_offset: 0.02
    padding_scale: 2.0
    #filtered_cloud_topic: filtered_cloud #Use only for debugging
